from pydantic import BaseModel, ConfigDict, Field

# creating and returning post
class PostBase(BaseModel):
    # type hints
    title: str = Field(min_length=1, max_length=100)
    content: str = Field(min_length=1)
    author: str = Field(min_length=1, max_length=50)

# 
class PostCreate(PostBase):
    pass

# defines what response is given to user
class PostResponse(PostBase):
    # Pydantic can read data from arbitrary class instances (like ORM objects) 
    # by accessing attribute names, rather than requiring a dictionary-like structure.
    model_config = ConfigDict(from_attributes=True)

    # configs not provided by client,or fields that are generated by system
    # generally avoid 'id' since id is python built in, but here it wont conflict
    id: int 
    date_posted: str